
CREATE DATABASE IF NOT EXISTS ftamangaapi;

USE ftamangaapi;

CREATE TABLE IF NOT EXISTS products(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  price FLOAT NOT NULL DEFAULT 0,
  editorial VARCHAR(150) NOT NULL DEFAULT 'Desconocida',
  img VARCHAR(150) DEFAULT NULL,
  img_id VARCHAR(150) DEFAULT NULL,
  year INT NOT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  user VARCHAR(150) NOT NULL,
  password VARCHAR(150) NOT NULL,
  address VARCHAR(150) DEFAULT 'Desconocida',
  phone VARCHAR(150) DEFAULT 'Anonimo',
  email VARCHAR(150) NOT NULL UNIQUE,
  role ENUM('User', 'Admin') NOT NULL DEFAULT 'User',
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL
);